    <?php 
    $this->title = "Titel von: Menü css und alles zusammen Versuch!";
    $this->headTitle($this->title);
    ?>
<!--GedokTestZF8-->
<div id="rechtsbox">
    rechtsbox:<br><br>
</div>
<div id="rechtsNamensListenBox">
    rechtsNamensListenBox:<br>
        Gedok Künstlerinnen:<br>
    <span id="namensliste"> 
      alphabetisch <br><br>
    </span>         
<table>
<?php foreach($this->kuenstlerin as $kuenstlerin) : ?>

    <tr>
        <td>
        <span id="namensliste"> 
        <a href="
        <?php echo $this->escape($kuenstlerin->name) . ($kuenstlerin->vorname)?>
        ">     <?php echo $this->escape($kuenstlerin->name) . ', ' . ($kuenstlerin->vorname)?> </a>
        </span>  
        </td>
    </tr>
<?php endforeach; ?>
</table>

</div>

<div id="linksbox">
    <br><br>
    to do:<br>
<br> wohin die kuenstlerinnen-Liste?,<br> warum echo? <br> menues,<br> navigation, <br>css<br><br><br>
    erledigt: 
    <br>v layout
    <br>v datenbank
</div>
